{\rtf1\ansi\ansicpg1252\cocoartf1138\cocoasubrtf470
{\fonttbl\f0\fnil\fcharset0 Monaco;}
{\colortbl;\red255\green255\blue255;\red0\green0\blue128;\red255\green0\blue0;}
\margl1440\margr1440\vieww18860\viewh9720\viewkind0
\deftab720
\pard\pardeftab720

\f0\fs22 \cf0 14:47:47.739 [main] INFO  c.u.c.b.s.execution.Main - Getting data...\
14:47:55.733 [main] INFO  c.u.c.b.s.execution.Main - Encoding data...\
14:48:01.408 [main] INFO  c.u.c.b.s.execution.Main - Making station groups...\
14:48:04.517 [main] INFO  c.u.c.b.s.execution.Main - Creating cnf lookup...\
14:48:04.551 [main] INFO  c.u.c.b.s.execution.Main - Creating instance encoder...\
14:48:04.553 [main] INFO  c.u.c.b.s.execution.Main - Creating solver...\
14:48:06.255 [main] DEBUG c.u.c.b.a.t.c.CommandLineTargetAlgorithmEvaluator - Initalized with the following Execution Configuration algoExec:python solverwrapper.py\
AlgorithmExecutionDirectory:/Users/narnosti/Documents/fcc-station-packing/FCCStationPacking/SATsolvers/\
ParamFile:/Users/narnosti/Documents/fcc-station-packing/FCCStationPacking/SATsolvers/sw_parameterspaces/sw_picosat.txt\
 Cluster:false\
Determininstic:false \
14:48:06.255 [main] DEBUG c.u.c.b.a.t.c.CommandLineTargetAlgorithmEvaluator - Concurrent Execution true\
14:48:06.258 [main] DEBUG c.u.c.b.a.t.TargetAlgorithmEvaluatorBuilder - Bounding the number of concurrent target algorithm evaluations to 4 \
14:48:06.261 [main] INFO  c.u.c.b.s.execution.Main - Creating experiment reporter...\
14:48:06.278 [main] INFO  c.u.c.b.s.execution.Main - Creating instance generation experiment...\
14:48:06.279 [main] INFO  c.u.c.b.s.execution.Main - Creating station iterator...\
14:48:06.336 [main] INFO  c.u.c.b.s.execution.Main - Getting starting stations...\
14:48:06.336 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Trying to add Station 61216 to current set.\
14:48:06.336 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Getting problem instance.\
14:48:06.336 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - Grouping stations.\
14:48:06.336 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - There are 1 groups.\
14:48:06.373 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Solving instance of size 1.\
14:48:06.385 [main] DEBUG c.u.c.b.a.t.d.BoundedTargetAlgorithmEvaluator - Asked for permission to run 1 things, got permission to run 1 things, total completed for this batch 0 \
14:48:06.387 [main] WARN  c.u.c.b.a.t.d.RetryCrashedRunsTargetAlgorithmEvaluator - Cannot retry runs that are asynchronous at the moment\
14:48:12.105 [pool-2-thread-1] DEBUG c.u.c.b.a.t.c.CommandLineTargetAlgorithmEvaluator - Using concurrent algorithm runner\
14:48:12.539 [pool-2-thread-1] WARN  c.u.c.b.a.a.CommandLineAlgorithmRun - This version of SMAC hardcodes run length for calls to the target algorithm to 2147483647.\
14:48:15.183 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected Call: cd /Users/narnosti/Documents/fcc-station-packing/FCCStationPacking/SATsolvers/ ;  python solverwrapper.py /Users/narnosti/Documents/fcc-station-packing/Output/CNFs/7ee55b71d880e20cfb3f9a9cd2b112e08b648742.cnf 0 1800.0 2147483647 0 -solver 'picosat' \
14:48:15.183 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected output last 4 lines\
14:48:15.195 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:15.196 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - /bin/sh: ./runsolver/runsolverx64/runsolver: cannot execute binary file\
14:48:15.196 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:15.196 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Result for ParamILS: CRASHED, 0.0333921909332, -1, -1, 0\
14:48:15.196 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Output complete\
\pard\pardeftab720
\cf2 \ul \ulc2 ca.ubc.cs.beta.aclib.exceptions.TargetAlgorithmAbortException\cf3 \ulnone : First Run Crashed : <Instance:0, Seed:0, Config:0x0004, Kappa:1800.0>\cf0 \
14:48:15.212 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Trying to add Station 61217 to current set.\
14:48:15.212 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Getting problem instance.\
14:48:15.212 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - Grouping stations.\
14:48:15.212 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - There are 1 groups.\
14:48:15.212 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Solving instance of size 2.\
14:48:15.213 [main] DEBUG c.u.c.b.a.t.d.BoundedTargetAlgorithmEvaluator - Asked for permission to run 1 things, got permission to run 1 things, total completed for this batch 0 \
14:48:15.213 [main] WARN  c.u.c.b.a.t.d.RetryCrashedRunsTargetAlgorithmEvaluator - Cannot retry runs that are asynchronous at the moment\
14:48:15.213 [pool-2-thread-1] DEBUG c.u.c.b.a.t.c.CommandLineTargetAlgorithmEvaluator - Using concurrent algorithm runner\
\cf3 	at ca.ubc.cs.beta.aclib.targetalgorithmevaluator.decorators.AbortOnFirstRunCrashTargetAlgorithmEvaluator.validate(\cf2 \ul AbortOnFirstRunCrashTargetAlgorithmEvaluator.java:66\cf3 \ulnone )\cf0 \
\cf3 	at ca.ubc.cs.beta.aclib.targetalgorithmevaluator.decorators.AbortOnFirstRunCrashTargetAlgorithmEvaluator.access$000(\cf2 \ul AbortOnFirstRunCrashTargetAlgorithmEvaluator.java:25\cf3 \ulnone )\cf0 \
\cf3 	at ca.ubc.cs.beta.aclib.targetalgorithmevaluator.decorators.AbortOnFirstRunCrashTargetAlgorithmEvaluator$1.onSuccess(\cf2 \ul AbortOnFirstRunCrashTargetAlgorithmEvaluator.java:96\cf3 \ulnone )\cf0 \
\cf3 	at ca.ubc.cs.beta.aclib.targetalgorithmevaluator.AbstractBlockingTargetAlgorithmEvaluator$1.run(\cf2 \ul AbstractBlockingTargetAlgorithmEvaluator.java:59\cf3 \ulnone )\cf0 \
\cf3 	at java.util.concurrent.ThreadPoolExecutor.runWorker(\cf2 \ul ThreadPoolExecutor.java:1145\cf3 \ulnone )\cf0 \
\cf3 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(\cf2 \ul ThreadPoolExecutor.java:615\cf3 \ulnone )\cf0 \
\cf3 	at java.lang.Thread.run(\cf2 \ul Thread.java:722\cf3 \ulnone )\cf0 \
14:48:15.271 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected Call: cd /Users/narnosti/Documents/fcc-station-packing/FCCStationPacking/SATsolvers/ ;  python solverwrapper.py /Users/narnosti/Documents/fcc-station-packing/Output/CNFs/9463b78a08e32a521300bd4106dd4f5ab2d34e32.cnf 0 1800.0 2147483647 0 -solver 'picosat' \
14:48:15.272 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected output last 4 lines\
14:48:15.272 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:15.272 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - /bin/sh: ./runsolver/runsolverx64/runsolver: cannot execute binary file\
14:48:15.272 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:15.272 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Result for ParamILS: CRASHED, 0.00101685523987, -1, -1, 0\
14:48:15.272 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Output complete\
14:48:15.290 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Result: CRASHED,0.00101685523987\
14:48:15.625 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Instance was UNSAT, removing station.\
14:48:15.625 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Trying to add Station 70414 to current set.\
14:48:15.625 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Getting problem instance.\
14:48:15.625 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - Grouping stations.\
14:48:15.626 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - There are 1 groups.\
14:48:15.626 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Solving instance of size 2.\
14:48:15.627 [main] DEBUG c.u.c.b.a.t.d.BoundedTargetAlgorithmEvaluator - Asked for permission to run 1 things, got permission to run 1 things, total completed for this batch 0 \
14:48:15.627 [main] WARN  c.u.c.b.a.t.d.RetryCrashedRunsTargetAlgorithmEvaluator - Cannot retry runs that are asynchronous at the moment\
14:48:15.627 [pool-2-thread-1] DEBUG c.u.c.b.a.t.c.CommandLineTargetAlgorithmEvaluator - Using concurrent algorithm runner\
14:48:15.688 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected Call: cd /Users/narnosti/Documents/fcc-station-packing/FCCStationPacking/SATsolvers/ ;  python solverwrapper.py /Users/narnosti/Documents/fcc-station-packing/Output/CNFs/f28f8ea5941eb667a5937337a32978004d478dc4.cnf 0 1800.0 2147483647 0 -solver 'picosat' \
14:48:15.688 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected output last 4 lines\
14:48:15.688 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:15.689 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - /bin/sh: ./runsolver/runsolverx64/runsolver: cannot execute binary file\
14:48:15.689 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:15.689 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Result for ParamILS: CRASHED, 0.00103712081909, -1, -1, 0\
14:48:15.689 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Output complete\
14:48:15.690 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Result: CRASHED,0.00103712081909\
14:48:15.690 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Instance was UNSAT, removing station.\
14:48:15.690 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Trying to add Station 70415 to current set.\
14:48:15.690 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Getting problem instance.\
14:48:15.690 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - Grouping stations.\
14:48:15.690 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - There are 1 groups.\
14:48:15.691 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Solving instance of size 2.\
14:48:15.691 [main] DEBUG c.u.c.b.a.t.d.BoundedTargetAlgorithmEvaluator - Asked for permission to run 1 things, got permission to run 1 things, total completed for this batch 0 \
14:48:15.691 [main] WARN  c.u.c.b.a.t.d.RetryCrashedRunsTargetAlgorithmEvaluator - Cannot retry runs that are asynchronous at the moment\
14:48:15.691 [pool-2-thread-1] DEBUG c.u.c.b.a.t.c.CommandLineTargetAlgorithmEvaluator - Using concurrent algorithm runner\
14:48:15.752 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected Call: cd /Users/narnosti/Documents/fcc-station-packing/FCCStationPacking/SATsolvers/ ;  python solverwrapper.py /Users/narnosti/Documents/fcc-station-packing/Output/CNFs/52a377786c3b62eb0387020a5f0b5d277f5b0f19.cnf 0 1800.0 2147483647 0 -solver 'picosat' \
14:48:15.753 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected output last 4 lines\
14:48:15.753 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:15.753 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - /bin/sh: ./runsolver/runsolverx64/runsolver: cannot execute binary file\
14:48:15.753 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:15.753 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Result for ParamILS: CRASHED, 0.000980138778687, -1, -1, 0\
14:48:15.753 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Output complete\
14:48:15.754 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Result: CRASHED,9.80138778687E-4\
14:48:15.754 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Instance was UNSAT, removing station.\
14:48:15.754 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Trying to add Station 17611 to current set.\
14:48:15.754 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Getting problem instance.\
14:48:15.755 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - Grouping stations.\
14:48:15.755 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - There are 1 groups.\
14:48:15.755 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Solving instance of size 2.\
14:48:15.756 [main] DEBUG c.u.c.b.a.t.d.BoundedTargetAlgorithmEvaluator - Asked for permission to run 1 things, got permission to run 1 things, total completed for this batch 0 \
14:48:15.756 [main] WARN  c.u.c.b.a.t.d.RetryCrashedRunsTargetAlgorithmEvaluator - Cannot retry runs that are asynchronous at the moment\
14:48:15.756 [pool-2-thread-1] DEBUG c.u.c.b.a.t.c.CommandLineTargetAlgorithmEvaluator - Using concurrent algorithm runner\
14:48:15.875 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected Call: cd /Users/narnosti/Documents/fcc-station-packing/FCCStationPacking/SATsolvers/ ;  python solverwrapper.py /Users/narnosti/Documents/fcc-station-packing/Output/CNFs/fbb0b679d88030195b8195f3ef1234a4c5333fe5.cnf 0 1800.0 2147483647 0 -solver 'picosat' \
14:48:15.876 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected output last 4 lines\
14:48:15.876 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:15.876 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - /bin/sh: ./runsolver/runsolverx64/runsolver: cannot execute binary file\
14:48:15.876 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:15.876 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Result for ParamILS: CRASHED, 0.00111103057861, -1, -1, 0\
14:48:15.876 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Output complete\
14:48:15.877 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Result: CRASHED,0.00111103057861\
14:48:15.877 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Instance was UNSAT, removing station.\
14:48:15.877 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Trying to add Station 70413 to current set.\
14:48:15.878 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Getting problem instance.\
14:48:15.878 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - Grouping stations.\
14:48:15.878 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - There are 1 groups.\
14:48:15.879 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Solving instance of size 2.\
14:48:15.879 [main] DEBUG c.u.c.b.a.t.d.BoundedTargetAlgorithmEvaluator - Asked for permission to run 1 things, got permission to run 1 things, total completed for this batch 0 \
14:48:15.880 [main] WARN  c.u.c.b.a.t.d.RetryCrashedRunsTargetAlgorithmEvaluator - Cannot retry runs that are asynchronous at the moment\
14:48:15.880 [pool-2-thread-1] DEBUG c.u.c.b.a.t.c.CommandLineTargetAlgorithmEvaluator - Using concurrent algorithm runner\
14:48:15.939 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected Call: cd /Users/narnosti/Documents/fcc-station-packing/FCCStationPacking/SATsolvers/ ;  python solverwrapper.py /Users/narnosti/Documents/fcc-station-packing/Output/CNFs/893e3e3ddf7009822ea53762a28af414fcd28326.cnf 0 1800.0 2147483647 0 -solver 'picosat' \
14:48:15.940 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected output last 4 lines\
14:48:15.940 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:15.940 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - /bin/sh: ./runsolver/runsolverx64/runsolver: cannot execute binary file\
14:48:15.940 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:15.940 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Result for ParamILS: CRASHED, 0.00108289718628, -1, -1, 0\
14:48:15.940 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Output complete\
14:48:15.941 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Result: CRASHED,0.00108289718628\
14:48:15.941 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Instance was UNSAT, removing station.\
14:48:15.941 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Trying to add Station 83707 to current set.\
14:48:15.942 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Getting problem instance.\
14:48:15.942 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - Grouping stations.\
14:48:15.942 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - There are 1 groups.\
14:48:15.942 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Solving instance of size 2.\
14:48:15.942 [main] DEBUG c.u.c.b.a.t.d.BoundedTargetAlgorithmEvaluator - Asked for permission to run 1 things, got permission to run 1 things, total completed for this batch 0 \
14:48:15.942 [main] WARN  c.u.c.b.a.t.d.RetryCrashedRunsTargetAlgorithmEvaluator - Cannot retry runs that are asynchronous at the moment\
14:48:15.943 [pool-2-thread-1] DEBUG c.u.c.b.a.t.c.CommandLineTargetAlgorithmEvaluator - Using concurrent algorithm runner\
14:48:16.003 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected Call: cd /Users/narnosti/Documents/fcc-station-packing/FCCStationPacking/SATsolvers/ ;  python solverwrapper.py /Users/narnosti/Documents/fcc-station-packing/Output/CNFs/cd4ba0f161e344a91554c1668196fe3df83db028.cnf 0 1800.0 2147483647 0 -solver 'picosat' \
14:48:16.003 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected output last 4 lines\
14:48:16.003 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:16.003 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - /bin/sh: ./runsolver/runsolverx64/runsolver: cannot execute binary file\
14:48:16.003 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:16.004 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Result for ParamILS: CRASHED, 0.00109386444092, -1, -1, 0\
14:48:16.004 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Output complete\
14:48:16.004 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Result: CRASHED,0.00109386444092\
14:48:17.391 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Instance was UNSAT, removing station.\
14:48:17.391 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Trying to add Station 70421 to current set.\
14:48:17.391 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Getting problem instance.\
14:48:17.391 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - Grouping stations.\
14:48:17.392 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - There are 1 groups.\
14:48:17.392 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Solving instance of size 2.\
14:48:17.392 [main] DEBUG c.u.c.b.a.t.d.BoundedTargetAlgorithmEvaluator - Asked for permission to run 1 things, got permission to run 1 things, total completed for this batch 0 \
14:48:17.392 [main] WARN  c.u.c.b.a.t.d.RetryCrashedRunsTargetAlgorithmEvaluator - Cannot retry runs that are asynchronous at the moment\
14:48:17.393 [pool-2-thread-1] DEBUG c.u.c.b.a.t.c.CommandLineTargetAlgorithmEvaluator - Using concurrent algorithm runner\
14:48:17.487 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected Call: cd /Users/narnosti/Documents/fcc-station-packing/FCCStationPacking/SATsolvers/ ;  python solverwrapper.py /Users/narnosti/Documents/fcc-station-packing/Output/CNFs/551b6111669dcfd21146850af7bd50df75a32b21.cnf 0 1800.0 2147483647 0 -solver 'picosat' \
14:48:17.488 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected output last 4 lines\
14:48:17.488 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:17.488 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - /bin/sh: ./runsolver/runsolverx64/runsolver: cannot execute binary file\
14:48:17.488 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:17.488 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Result for ParamILS: CRASHED, 0.0010929107666, -1, -1, 0\
14:48:17.488 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Output complete\
14:48:17.489 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Result: CRASHED,0.0010929107666\
14:48:17.489 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Instance was UNSAT, removing station.\
14:48:17.489 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Trying to add Station 70420 to current set.\
14:48:17.489 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Getting problem instance.\
14:48:17.489 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - Grouping stations.\
14:48:17.489 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - There are 1 groups.\
14:48:17.490 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Solving instance of size 2.\
14:48:17.490 [main] DEBUG c.u.c.b.a.t.d.BoundedTargetAlgorithmEvaluator - Asked for permission to run 1 things, got permission to run 1 things, total completed for this batch 0 \
14:48:17.490 [main] WARN  c.u.c.b.a.t.d.RetryCrashedRunsTargetAlgorithmEvaluator - Cannot retry runs that are asynchronous at the moment\
14:48:17.490 [pool-2-thread-1] DEBUG c.u.c.b.a.t.c.CommandLineTargetAlgorithmEvaluator - Using concurrent algorithm runner\
14:48:17.667 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected Call: cd /Users/narnosti/Documents/fcc-station-packing/FCCStationPacking/SATsolvers/ ;  python solverwrapper.py /Users/narnosti/Documents/fcc-station-packing/Output/CNFs/9cf7890bc18dc4034ced5d0e306f86fc66b0165b.cnf 0 1800.0 2147483647 0 -solver 'picosat' \
14:48:17.668 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected output last 4 lines\
14:48:17.668 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:17.668 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - /bin/sh: ./runsolver/runsolverx64/runsolver: cannot execute binary file\
14:48:17.668 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:17.668 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Result for ParamILS: CRASHED, 0.00117611885071, -1, -1, 0\
14:48:17.668 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Output complete\
14:48:17.669 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Result: CRASHED,0.00117611885071\
14:48:17.675 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Instance was UNSAT, removing station.\
14:48:17.675 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Trying to add Station 70419 to current set.\
14:48:17.675 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Getting problem instance.\
14:48:17.675 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - Grouping stations.\
14:48:17.675 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - There are 1 groups.\
14:48:17.676 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Solving instance of size 2.\
14:48:17.676 [main] DEBUG c.u.c.b.a.t.d.BoundedTargetAlgorithmEvaluator - Asked for permission to run 1 things, got permission to run 1 things, total completed for this batch 0 \
14:48:17.676 [main] WARN  c.u.c.b.a.t.d.RetryCrashedRunsTargetAlgorithmEvaluator - Cannot retry runs that are asynchronous at the moment\
14:48:17.677 [pool-2-thread-1] DEBUG c.u.c.b.a.t.c.CommandLineTargetAlgorithmEvaluator - Using concurrent algorithm runner\
14:48:17.792 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected Call: cd /Users/narnosti/Documents/fcc-station-packing/FCCStationPacking/SATsolvers/ ;  python solverwrapper.py /Users/narnosti/Documents/fcc-station-packing/Output/CNFs/84239faf298dabc08c6a1c6fac84b50c31906fb1.cnf 0 1800.0 2147483647 0 -solver 'picosat' \
14:48:17.792 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected output last 4 lines\
14:48:17.792 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:17.792 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - /bin/sh: ./runsolver/runsolverx64/runsolver: cannot execute binary file\
14:48:17.792 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:17.792 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Result for ParamILS: CRASHED, 0.0011568069458, -1, -1, 0\
14:48:17.792 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Output complete\
14:48:17.793 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Result: CRASHED,0.0011568069458\
14:48:17.794 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Instance was UNSAT, removing station.\
14:48:17.794 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Trying to add Station 70416 to current set.\
14:48:17.794 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Getting problem instance.\
14:48:17.794 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - Grouping stations.\
14:48:17.794 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - There are 1 groups.\
14:48:17.795 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Solving instance of size 2.\
14:48:17.795 [main] DEBUG c.u.c.b.a.t.d.BoundedTargetAlgorithmEvaluator - Asked for permission to run 1 things, got permission to run 1 things, total completed for this batch 0 \
14:48:17.795 [main] WARN  c.u.c.b.a.t.d.RetryCrashedRunsTargetAlgorithmEvaluator - Cannot retry runs that are asynchronous at the moment\
14:48:17.795 [pool-2-thread-1] DEBUG c.u.c.b.a.t.c.CommandLineTargetAlgorithmEvaluator - Using concurrent algorithm runner\
14:48:17.868 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected Call: cd /Users/narnosti/Documents/fcc-station-packing/FCCStationPacking/SATsolvers/ ;  python solverwrapper.py /Users/narnosti/Documents/fcc-station-packing/Output/CNFs/bbd7b0a322fe6097e11167b7ba55b0c181fd13c8.cnf 0 1800.0 2147483647 0 -solver 'picosat' \
14:48:17.869 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected output last 4 lines\
14:48:17.869 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:17.869 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - /bin/sh: ./runsolver/runsolverx64/runsolver: cannot execute binary file\
14:48:17.869 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:17.869 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Result for ParamILS: CRASHED, 0.00109887123108, -1, -1, 0\
14:48:17.869 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Output complete\
14:48:17.870 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Result: CRASHED,0.00109887123108\
14:48:18.221 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Instance was UNSAT, removing station.\
14:48:18.221 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Trying to add Station 30601 to current set.\
14:48:18.221 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Getting problem instance.\
14:48:18.221 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - Grouping stations.\
14:48:18.221 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - There are 2 groups.\
14:48:18.222 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Solving instance of size 2.\
14:48:18.222 [main] DEBUG c.u.c.b.a.t.d.BoundedTargetAlgorithmEvaluator - Asked for permission to run 2 things, got permission to run 2 things, total completed for this batch 0 \
14:48:18.222 [main] WARN  c.u.c.b.a.t.d.RetryCrashedRunsTargetAlgorithmEvaluator - Cannot retry runs that are asynchronous at the moment\
14:48:18.222 [pool-2-thread-1] DEBUG c.u.c.b.a.t.c.CommandLineTargetAlgorithmEvaluator - Using concurrent algorithm runner\
14:48:18.222 [pool-2-thread-1] DEBUG c.u.c.b.a.a.AutomaticConfiguratorFactory - Concurrent Algorithm Runner created allowing \{\} threads\
14:48:18.224 [pool-2-thread-1] DEBUG c.u.c.b.a.a.ConcurrentAlgorithmRunner - Creating Thread Pool Supporting 4\
14:48:20.148 [pool-28-thread-2] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected Call: cd /Users/narnosti/Documents/fcc-station-packing/FCCStationPacking/SATsolvers/ ;  python solverwrapper.py /Users/narnosti/Documents/fcc-station-packing/Output/CNFs/b7fda7a2b68882977df5b4c07ebc2351815d2bb0.cnf 0 1800.0 2147483647 0 -solver 'picosat' \
14:48:20.149 [pool-28-thread-2] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected output last 4 lines\
14:48:20.149 [pool-28-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected Call: cd /Users/narnosti/Documents/fcc-station-packing/FCCStationPacking/SATsolvers/ ;  python solverwrapper.py /Users/narnosti/Documents/fcc-station-packing/Output/CNFs/7ee55b71d880e20cfb3f9a9cd2b112e08b648742.cnf 0 1800.0 2147483647 0 -solver 'picosat' \
14:48:20.149 [pool-28-thread-2] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:20.149 [pool-28-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected output last 4 lines\
14:48:20.149 [pool-28-thread-2] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - /bin/sh: ./runsolver/runsolverx64/runsolver: cannot execute binary file\
14:48:20.149 [pool-28-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:20.149 [pool-28-thread-2] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:20.149 [pool-28-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - /bin/sh: ./runsolver/runsolverx64/runsolver: cannot execute binary file\
14:48:20.149 [pool-28-thread-2] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Result for ParamILS: CRASHED, 0.001305103302, -1, -1, 0\
14:48:20.149 [pool-28-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:20.149 [pool-28-thread-2] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Output complete\
14:48:20.149 [pool-28-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Result for ParamILS: CRASHED, 0.00115084648132, -1, -1, 0\
14:48:20.149 [pool-28-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Output complete\
14:48:20.151 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Result: CRASHED,0.00245594978332\
14:48:20.152 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Instance was UNSAT, removing station.\
14:48:20.152 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Trying to add Station 17625 to current set.\
14:48:20.152 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Getting problem instance.\
14:48:20.152 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - Grouping stations.\
14:48:20.152 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - There are 1 groups.\
14:48:20.152 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Solving instance of size 2.\
14:48:20.153 [main] DEBUG c.u.c.b.a.t.d.BoundedTargetAlgorithmEvaluator - Asked for permission to run 1 things, got permission to run 1 things, total completed for this batch 0 \
14:48:20.153 [main] WARN  c.u.c.b.a.t.d.RetryCrashedRunsTargetAlgorithmEvaluator - Cannot retry runs that are asynchronous at the moment\
14:48:20.153 [pool-2-thread-1] DEBUG c.u.c.b.a.t.c.CommandLineTargetAlgorithmEvaluator - Using concurrent algorithm runner\
14:48:20.436 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected Call: cd /Users/narnosti/Documents/fcc-station-packing/FCCStationPacking/SATsolvers/ ;  python solverwrapper.py /Users/narnosti/Documents/fcc-station-packing/Output/CNFs/eb564a1195cfd6131f8d00787c5d63ce763b49d8.cnf 0 1800.0 2147483647 0 -solver 'picosat' \
14:48:20.436 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected output last 4 lines\
14:48:20.436 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:20.436 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - /bin/sh: ./runsolver/runsolverx64/runsolver: cannot execute binary file\
14:48:20.436 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:20.436 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Result for ParamILS: CRASHED, 0.00100708007812, -1, -1, 0\
14:48:20.436 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Output complete\
14:48:20.437 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Result: CRASHED,0.00100708007812\
14:48:20.438 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Instance was UNSAT, removing station.\
14:48:20.438 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Trying to add Station 70430 to current set.\
14:48:20.438 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Getting problem instance.\
14:48:20.438 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - Grouping stations.\
14:48:20.438 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - There are 1 groups.\
14:48:20.438 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Solving instance of size 2.\
14:48:20.439 [main] DEBUG c.u.c.b.a.t.d.BoundedTargetAlgorithmEvaluator - Asked for permission to run 1 things, got permission to run 1 things, total completed for this batch 0 \
14:48:20.439 [main] WARN  c.u.c.b.a.t.d.RetryCrashedRunsTargetAlgorithmEvaluator - Cannot retry runs that are asynchronous at the moment\
14:48:20.439 [pool-2-thread-1] DEBUG c.u.c.b.a.t.c.CommandLineTargetAlgorithmEvaluator - Using concurrent algorithm runner\
14:48:20.508 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected Call: cd /Users/narnosti/Documents/fcc-station-packing/FCCStationPacking/SATsolvers/ ;  python solverwrapper.py /Users/narnosti/Documents/fcc-station-packing/Output/CNFs/373d606039fa7b65e82c940ff8bc0fb2ac4ae36e.cnf 0 1800.0 2147483647 0 -solver 'picosat' \
14:48:20.508 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected output last 4 lines\
14:48:20.508 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:20.508 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - /bin/sh: ./runsolver/runsolverx64/runsolver: cannot execute binary file\
14:48:20.508 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:20.508 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Result for ParamILS: CRASHED, 0.00122404098511, -1, -1, 0\
14:48:20.508 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Output complete\
14:48:20.509 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Result: CRASHED,0.00122404098511\
14:48:20.510 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Instance was UNSAT, removing station.\
14:48:20.510 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Trying to add Station 70429 to current set.\
14:48:20.510 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Getting problem instance.\
14:48:20.510 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - Grouping stations.\
14:48:20.510 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - There are 1 groups.\
14:48:20.511 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Solving instance of size 2.\
14:48:20.511 [main] DEBUG c.u.c.b.a.t.d.BoundedTargetAlgorithmEvaluator - Asked for permission to run 1 things, got permission to run 1 things, total completed for this batch 0 \
14:48:20.511 [main] WARN  c.u.c.b.a.t.d.RetryCrashedRunsTargetAlgorithmEvaluator - Cannot retry runs that are asynchronous at the moment\
14:48:20.511 [pool-2-thread-1] DEBUG c.u.c.b.a.t.c.CommandLineTargetAlgorithmEvaluator - Using concurrent algorithm runner\
14:48:22.563 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected Call: cd /Users/narnosti/Documents/fcc-station-packing/FCCStationPacking/SATsolvers/ ;  python solverwrapper.py /Users/narnosti/Documents/fcc-station-packing/Output/CNFs/be97f572fcdaef8c79f7237d44cd72f9f36df365.cnf 0 1800.0 2147483647 0 -solver 'picosat' \
14:48:22.564 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected output last 4 lines\
14:48:22.564 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:22.564 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - /bin/sh: ./runsolver/runsolverx64/runsolver: cannot execute binary file\
14:48:22.564 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:22.564 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Result for ParamILS: CRASHED, 0.00138401985168, -1, -1, 0\
14:48:22.564 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Output complete\
14:48:22.565 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Result: CRASHED,0.00138401985168\
14:48:22.631 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Instance was UNSAT, removing station.\
14:48:22.631 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Trying to add Station 70428 to current set.\
14:48:22.631 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Getting problem instance.\
14:48:22.631 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - Grouping stations.\
14:48:22.631 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - There are 1 groups.\
14:48:22.632 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Solving instance of size 2.\
14:48:22.632 [main] DEBUG c.u.c.b.a.t.d.BoundedTargetAlgorithmEvaluator - Asked for permission to run 1 things, got permission to run 1 things, total completed for this batch 0 \
14:48:22.632 [main] WARN  c.u.c.b.a.t.d.RetryCrashedRunsTargetAlgorithmEvaluator - Cannot retry runs that are asynchronous at the moment\
14:48:22.632 [pool-2-thread-1] DEBUG c.u.c.b.a.t.c.CommandLineTargetAlgorithmEvaluator - Using concurrent algorithm runner\
14:48:23.005 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected Call: cd /Users/narnosti/Documents/fcc-station-packing/FCCStationPacking/SATsolvers/ ;  python solverwrapper.py /Users/narnosti/Documents/fcc-station-packing/Output/CNFs/abbe67665e9f14f9c292a5673f57f3cbb5e936dd.cnf 0 1800.0 2147483647 0 -solver 'picosat' \
14:48:23.005 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected output last 4 lines\
14:48:23.005 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:23.005 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - /bin/sh: ./runsolver/runsolverx64/runsolver: cannot execute binary file\
14:48:23.005 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:23.005 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Result for ParamILS: CRASHED, 0.000961065292358, -1, -1, 0\
14:48:23.005 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Output complete\
14:48:23.006 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Result: CRASHED,9.61065292358E-4\
14:48:23.007 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Instance was UNSAT, removing station.\
14:48:23.007 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Trying to add Station 70427 to current set.\
14:48:23.007 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Getting problem instance.\
14:48:23.007 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - Grouping stations.\
14:48:23.007 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - There are 1 groups.\
14:48:23.008 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Solving instance of size 2.\
14:48:23.008 [main] DEBUG c.u.c.b.a.t.d.BoundedTargetAlgorithmEvaluator - Asked for permission to run 1 things, got permission to run 1 things, total completed for this batch 0 \
14:48:23.008 [main] WARN  c.u.c.b.a.t.d.RetryCrashedRunsTargetAlgorithmEvaluator - Cannot retry runs that are asynchronous at the moment\
14:48:23.008 [pool-2-thread-1] DEBUG c.u.c.b.a.t.c.CommandLineTargetAlgorithmEvaluator - Using concurrent algorithm runner\
14:48:23.070 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected Call: cd /Users/narnosti/Documents/fcc-station-packing/FCCStationPacking/SATsolvers/ ;  python solverwrapper.py /Users/narnosti/Documents/fcc-station-packing/Output/CNFs/e78bd474408a9a6a47a769aa45f8673b0b943b0d.cnf 0 1800.0 2147483647 0 -solver 'picosat' \
14:48:23.070 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected output last 4 lines\
14:48:23.070 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:23.070 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - /bin/sh: ./runsolver/runsolverx64/runsolver: cannot execute binary file\
14:48:23.070 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:23.071 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Result for ParamILS: CRASHED, 0.000963926315308, -1, -1, 0\
14:48:23.071 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Output complete\
14:48:23.072 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Result: CRASHED,9.63926315308E-4\
14:48:23.072 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Instance was UNSAT, removing station.\
14:48:23.072 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Trying to add Station 70425 to current set.\
14:48:23.072 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Getting problem instance.\
14:48:23.072 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - Grouping stations.\
14:48:23.072 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - There are 1 groups.\
14:48:23.073 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Solving instance of size 2.\
14:48:23.073 [main] DEBUG c.u.c.b.a.t.d.BoundedTargetAlgorithmEvaluator - Asked for permission to run 1 things, got permission to run 1 things, total completed for this batch 0 \
14:48:23.073 [main] WARN  c.u.c.b.a.t.d.RetryCrashedRunsTargetAlgorithmEvaluator - Cannot retry runs that are asynchronous at the moment\
14:48:23.073 [pool-2-thread-1] DEBUG c.u.c.b.a.t.c.CommandLineTargetAlgorithmEvaluator - Using concurrent algorithm runner\
14:48:23.133 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected Call: cd /Users/narnosti/Documents/fcc-station-packing/FCCStationPacking/SATsolvers/ ;  python solverwrapper.py /Users/narnosti/Documents/fcc-station-packing/Output/CNFs/8ff62565d795c7ca568994fdf93283ed7e717e9d.cnf 0 1800.0 2147483647 0 -solver 'picosat' \
14:48:23.134 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected output last 4 lines\
14:48:23.134 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:23.134 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - /bin/sh: ./runsolver/runsolverx64/runsolver: cannot execute binary file\
14:48:23.134 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:23.134 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Result for ParamILS: CRASHED, 0.00104212760925, -1, -1, 0\
14:48:23.134 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Output complete\
14:48:23.136 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Result: CRASHED,0.00104212760925\
14:48:23.136 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Instance was UNSAT, removing station.\
14:48:23.137 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Trying to add Station 65074 to current set.\
14:48:23.137 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Getting problem instance.\
14:48:23.137 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - Grouping stations.\
14:48:23.137 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - There are 1 groups.\
14:48:23.138 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Solving instance of size 2.\
14:48:23.138 [main] DEBUG c.u.c.b.a.t.d.BoundedTargetAlgorithmEvaluator - Asked for permission to run 1 things, got permission to run 1 things, total completed for this batch 0 \
14:48:23.138 [main] WARN  c.u.c.b.a.t.d.RetryCrashedRunsTargetAlgorithmEvaluator - Cannot retry runs that are asynchronous at the moment\
14:48:23.138 [pool-2-thread-1] DEBUG c.u.c.b.a.t.c.CommandLineTargetAlgorithmEvaluator - Using concurrent algorithm runner\
14:48:23.208 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected Call: cd /Users/narnosti/Documents/fcc-station-packing/FCCStationPacking/SATsolvers/ ;  python solverwrapper.py /Users/narnosti/Documents/fcc-station-packing/Output/CNFs/0e683c740d734d0f07e4f0db760152939c6195a0.cnf 0 1800.0 2147483647 0 -solver 'picosat' \
14:48:23.208 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected output last 4 lines\
14:48:23.208 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:23.208 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - /bin/sh: ./runsolver/runsolverx64/runsolver: cannot execute binary file\
14:48:23.208 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:23.209 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Result for ParamILS: CRASHED, 0.00101089477539, -1, -1, 0\
14:48:23.209 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Output complete\
14:48:23.210 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Result: CRASHED,0.00101089477539\
14:48:23.226 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Instance was UNSAT, removing station.\
14:48:23.226 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Trying to add Station 52579 to current set.\
14:48:23.227 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Getting problem instance.\
14:48:23.227 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - Grouping stations.\
14:48:23.227 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - There are 1 groups.\
14:48:23.228 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Solving instance of size 2.\
14:48:23.228 [main] DEBUG c.u.c.b.a.t.d.BoundedTargetAlgorithmEvaluator - Asked for permission to run 1 things, got permission to run 1 things, total completed for this batch 0 \
14:48:23.228 [main] WARN  c.u.c.b.a.t.d.RetryCrashedRunsTargetAlgorithmEvaluator - Cannot retry runs that are asynchronous at the moment\
14:48:23.228 [pool-2-thread-1] DEBUG c.u.c.b.a.t.c.CommandLineTargetAlgorithmEvaluator - Using concurrent algorithm runner\
14:48:23.299 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected Call: cd /Users/narnosti/Documents/fcc-station-packing/FCCStationPacking/SATsolvers/ ;  python solverwrapper.py /Users/narnosti/Documents/fcc-station-packing/Output/CNFs/5c84c200c651a9f4313bcea11dae8cf08db11500.cnf 0 1800.0 2147483647 0 -solver 'picosat' \
14:48:23.299 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected output last 4 lines\
14:48:23.299 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:23.299 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - /bin/sh: ./runsolver/runsolverx64/runsolver: cannot execute binary file\
14:48:23.299 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:23.299 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Result for ParamILS: CRASHED, 0.000921964645386, -1, -1, 0\
14:48:23.299 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Output complete\
14:48:23.300 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Result: CRASHED,9.21964645386E-4\
14:48:23.301 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Instance was UNSAT, removing station.\
14:48:23.301 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Trying to add Station 26249 to current set.\
14:48:23.301 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Getting problem instance.\
14:48:23.301 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - Grouping stations.\
14:48:23.301 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - There are 2 groups.\
14:48:23.302 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Solving instance of size 2.\
14:48:23.302 [main] DEBUG c.u.c.b.a.t.d.BoundedTargetAlgorithmEvaluator - Asked for permission to run 2 things, got permission to run 2 things, total completed for this batch 0 \
14:48:23.302 [main] WARN  c.u.c.b.a.t.d.RetryCrashedRunsTargetAlgorithmEvaluator - Cannot retry runs that are asynchronous at the moment\
14:48:23.302 [pool-2-thread-1] DEBUG c.u.c.b.a.t.c.CommandLineTargetAlgorithmEvaluator - Using concurrent algorithm runner\
14:48:23.302 [pool-2-thread-1] DEBUG c.u.c.b.a.a.AutomaticConfiguratorFactory - Concurrent Algorithm Runner created allowing \{\} threads\
14:48:23.303 [pool-2-thread-1] DEBUG c.u.c.b.a.a.ConcurrentAlgorithmRunner - Creating Thread Pool Supporting 4\
14:48:23.382 [pool-48-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected Call: cd /Users/narnosti/Documents/fcc-station-packing/FCCStationPacking/SATsolvers/ ;  python solverwrapper.py /Users/narnosti/Documents/fcc-station-packing/Output/CNFs/7ee55b71d880e20cfb3f9a9cd2b112e08b648742.cnf 0 1800.0 2147483647 0 -solver 'picosat' \
14:48:23.382 [pool-48-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected output last 4 lines\
14:48:23.383 [pool-48-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:23.383 [pool-48-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - /bin/sh: ./runsolver/runsolverx64/runsolver: cannot execute binary file\
14:48:23.383 [pool-48-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:23.383 [pool-48-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Result for ParamILS: CRASHED, 0.00150609016418, -1, -1, 0\
14:48:23.383 [pool-48-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Output complete\
14:48:23.387 [pool-48-thread-2] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected Call: cd /Users/narnosti/Documents/fcc-station-packing/FCCStationPacking/SATsolvers/ ;  python solverwrapper.py /Users/narnosti/Documents/fcc-station-packing/Output/CNFs/c17538420c104ad472105f0dc46a8a620943990e.cnf 0 1800.0 2147483647 0 -solver 'picosat' \
14:48:23.387 [pool-48-thread-2] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected output last 4 lines\
14:48:23.387 [pool-48-thread-2] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:23.387 [pool-48-thread-2] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - /bin/sh: ./runsolver/runsolverx64/runsolver: cannot execute binary file\
14:48:23.387 [pool-48-thread-2] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:23.387 [pool-48-thread-2] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Result for ParamILS: CRASHED, 0.00112009048462, -1, -1, 0\
14:48:23.387 [pool-48-thread-2] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Output complete\
14:48:23.388 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Result: CRASHED,0.0026261806488\
14:48:23.392 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Instance was UNSAT, removing station.\
14:48:23.392 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Trying to add Station 56384 to current set.\
14:48:23.392 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Getting problem instance.\
14:48:23.392 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - Grouping stations.\
14:48:23.393 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - There are 2 groups.\
14:48:23.393 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Solving instance of size 2.\
14:48:23.394 [main] DEBUG c.u.c.b.a.t.d.BoundedTargetAlgorithmEvaluator - Asked for permission to run 2 things, got permission to run 2 things, total completed for this batch 0 \
14:48:23.394 [main] WARN  c.u.c.b.a.t.d.RetryCrashedRunsTargetAlgorithmEvaluator - Cannot retry runs that are asynchronous at the moment\
14:48:23.394 [pool-2-thread-1] DEBUG c.u.c.b.a.t.c.CommandLineTargetAlgorithmEvaluator - Using concurrent algorithm runner\
14:48:23.394 [pool-2-thread-1] DEBUG c.u.c.b.a.a.AutomaticConfiguratorFactory - Concurrent Algorithm Runner created allowing \{\} threads\
14:48:23.395 [pool-2-thread-1] DEBUG c.u.c.b.a.a.ConcurrentAlgorithmRunner - Creating Thread Pool Supporting 4\
14:48:23.481 [pool-52-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected Call: cd /Users/narnosti/Documents/fcc-station-packing/FCCStationPacking/SATsolvers/ ;  python solverwrapper.py /Users/narnosti/Documents/fcc-station-packing/Output/CNFs/86cefdcbbe6e9620b6ed90ac0ceb1d9b6932b6a4.cnf 0 1800.0 2147483647 0 -solver 'picosat' \
14:48:23.481 [pool-52-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected output last 4 lines\
14:48:23.481 [pool-52-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:23.481 [pool-52-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - /bin/sh: ./runsolver/runsolverx64/runsolver: cannot execute binary file\
14:48:23.481 [pool-52-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:23.481 [pool-52-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Result for ParamILS: CRASHED, 0.00111985206604, -1, -1, 0\
14:48:23.481 [pool-52-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Output complete\
14:48:23.483 [pool-52-thread-2] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected Call: cd /Users/narnosti/Documents/fcc-station-packing/FCCStationPacking/SATsolvers/ ;  python solverwrapper.py /Users/narnosti/Documents/fcc-station-packing/Output/CNFs/7ee55b71d880e20cfb3f9a9cd2b112e08b648742.cnf 0 1800.0 2147483647 0 -solver 'picosat' \
14:48:23.483 [pool-52-thread-2] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected output last 4 lines\
14:48:23.483 [pool-52-thread-2] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:23.484 [pool-52-thread-2] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - /bin/sh: ./runsolver/runsolverx64/runsolver: cannot execute binary file\
14:48:23.484 [pool-52-thread-2] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:23.484 [pool-52-thread-2] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Result for ParamILS: CRASHED, 0.000991106033325, -1, -1, 0\
14:48:23.484 [pool-52-thread-2] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Output complete\
14:48:23.484 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Result: CRASHED,0.002110958099365\
14:48:23.485 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Instance was UNSAT, removing station.\
14:48:23.485 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Trying to add Station 4354 to current set.\
14:48:23.485 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Getting problem instance.\
14:48:23.485 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - Grouping stations.\
14:48:23.485 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - There are 1 groups.\
14:48:23.486 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Solving instance of size 2.\
14:48:23.486 [main] DEBUG c.u.c.b.a.t.d.BoundedTargetAlgorithmEvaluator - Asked for permission to run 1 things, got permission to run 1 things, total completed for this batch 0 \
14:48:23.486 [main] WARN  c.u.c.b.a.t.d.RetryCrashedRunsTargetAlgorithmEvaluator - Cannot retry runs that are asynchronous at the moment\
14:48:23.486 [pool-2-thread-1] DEBUG c.u.c.b.a.t.c.CommandLineTargetAlgorithmEvaluator - Using concurrent algorithm runner\
14:48:23.551 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected Call: cd /Users/narnosti/Documents/fcc-station-packing/FCCStationPacking/SATsolvers/ ;  python solverwrapper.py /Users/narnosti/Documents/fcc-station-packing/Output/CNFs/530eebd9a9eec03a5915539b5f72d2d889837fa6.cnf 0 1800.0 2147483647 0 -solver 'picosat' \
14:48:23.551 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected output last 4 lines\
14:48:23.551 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:23.551 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - /bin/sh: ./runsolver/runsolverx64/runsolver: cannot execute binary file\
14:48:23.551 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:23.551 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Result for ParamILS: CRASHED, 0.000863790512085, -1, -1, 0\
14:48:23.551 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Output complete\
14:48:23.552 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Result: CRASHED,8.63790512085E-4\
14:48:23.553 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Instance was UNSAT, removing station.\
14:48:23.553 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Trying to add Station 4353 to current set.\
14:48:23.553 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Getting problem instance.\
14:48:23.553 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - Grouping stations.\
14:48:23.553 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - There are 1 groups.\
14:48:23.553 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Solving instance of size 2.\
14:48:23.554 [main] DEBUG c.u.c.b.a.t.d.BoundedTargetAlgorithmEvaluator - Asked for permission to run 1 things, got permission to run 1 things, total completed for this batch 0 \
14:48:23.554 [main] WARN  c.u.c.b.a.t.d.RetryCrashedRunsTargetAlgorithmEvaluator - Cannot retry runs that are asynchronous at the moment\
14:48:23.554 [pool-2-thread-1] DEBUG c.u.c.b.a.t.c.CommandLineTargetAlgorithmEvaluator - Using concurrent algorithm runner\
14:48:23.613 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected Call: cd /Users/narnosti/Documents/fcc-station-packing/FCCStationPacking/SATsolvers/ ;  python solverwrapper.py /Users/narnosti/Documents/fcc-station-packing/Output/CNFs/52451778ab356e36fa5225cc2fa035d4a70c4892.cnf 0 1800.0 2147483647 0 -solver 'picosat' \
14:48:23.613 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected output last 4 lines\
14:48:23.613 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:23.613 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - /bin/sh: ./runsolver/runsolverx64/runsolver: cannot execute binary file\
14:48:23.613 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:23.613 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Result for ParamILS: CRASHED, 0.000892877578735, -1, -1, 0\
14:48:23.613 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Output complete\
14:48:23.614 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Result: CRASHED,8.92877578735E-4\
14:48:23.615 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Instance was UNSAT, removing station.\
14:48:23.615 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Trying to add Station 4352 to current set.\
14:48:23.615 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Getting problem instance.\
14:48:23.615 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - Grouping stations.\
14:48:23.615 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - There are 2 groups.\
14:48:23.616 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Solving instance of size 2.\
14:48:23.616 [main] DEBUG c.u.c.b.a.t.d.BoundedTargetAlgorithmEvaluator - Asked for permission to run 2 things, got permission to run 2 things, total completed for this batch 0 \
14:48:23.616 [main] WARN  c.u.c.b.a.t.d.RetryCrashedRunsTargetAlgorithmEvaluator - Cannot retry runs that are asynchronous at the moment\
14:48:23.616 [pool-2-thread-1] DEBUG c.u.c.b.a.t.c.CommandLineTargetAlgorithmEvaluator - Using concurrent algorithm runner\
14:48:23.616 [pool-2-thread-1] DEBUG c.u.c.b.a.a.AutomaticConfiguratorFactory - Concurrent Algorithm Runner created allowing \{\} threads\
14:48:23.617 [pool-2-thread-1] DEBUG c.u.c.b.a.a.ConcurrentAlgorithmRunner - Creating Thread Pool Supporting 4\
14:48:23.700 [pool-60-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected Call: cd /Users/narnosti/Documents/fcc-station-packing/FCCStationPacking/SATsolvers/ ;  python solverwrapper.py /Users/narnosti/Documents/fcc-station-packing/Output/CNFs/7ee55b71d880e20cfb3f9a9cd2b112e08b648742.cnf 0 1800.0 2147483647 0 -solver 'picosat' \
14:48:23.700 [pool-60-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected output last 4 lines\
14:48:23.700 [pool-60-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:23.700 [pool-60-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - /bin/sh: ./runsolver/runsolverx64/runsolver: cannot execute binary file\
14:48:23.700 [pool-60-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:23.701 [pool-60-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Result for ParamILS: CRASHED, 0.00100898742676, -1, -1, 0\
14:48:23.701 [pool-60-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Output complete\
14:48:23.703 [pool-60-thread-2] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected Call: cd /Users/narnosti/Documents/fcc-station-packing/FCCStationPacking/SATsolvers/ ;  python solverwrapper.py /Users/narnosti/Documents/fcc-station-packing/Output/CNFs/26ef44254c3cee20c078e2daedd633e78ddbffe2.cnf 0 1800.0 2147483647 0 -solver 'picosat' \
14:48:23.703 [pool-60-thread-2] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected output last 4 lines\
14:48:23.703 [pool-60-thread-2] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:23.703 [pool-60-thread-2] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - /bin/sh: ./runsolver/runsolverx64/runsolver: cannot execute binary file\
14:48:23.703 [pool-60-thread-2] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:23.703 [pool-60-thread-2] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Result for ParamILS: CRASHED, 0.000986099243164, -1, -1, 0\
14:48:23.704 [pool-60-thread-2] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Output complete\
14:48:23.704 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Result: CRASHED,0.001995086669924\
14:48:23.705 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Instance was UNSAT, removing station.\
14:48:23.705 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Trying to add Station 35255 to current set.\
14:48:23.705 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Getting problem instance.\
14:48:23.705 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - Grouping stations.\
14:48:23.705 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - There are 1 groups.\
14:48:23.706 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Solving instance of size 2.\
14:48:23.706 [main] DEBUG c.u.c.b.a.t.d.BoundedTargetAlgorithmEvaluator - Asked for permission to run 1 things, got permission to run 1 things, total completed for this batch 0 \
14:48:23.706 [main] WARN  c.u.c.b.a.t.d.RetryCrashedRunsTargetAlgorithmEvaluator - Cannot retry runs that are asynchronous at the moment\
14:48:23.706 [pool-2-thread-1] DEBUG c.u.c.b.a.t.c.CommandLineTargetAlgorithmEvaluator - Using concurrent algorithm runner\
14:48:23.766 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected Call: cd /Users/narnosti/Documents/fcc-station-packing/FCCStationPacking/SATsolvers/ ;  python solverwrapper.py /Users/narnosti/Documents/fcc-station-packing/Output/CNFs/9fd4fa815d1e584de07909b34f5805b9c57b13f9.cnf 0 1800.0 2147483647 0 -solver 'picosat' \
14:48:23.767 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected output last 4 lines\
14:48:23.767 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:23.767 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - /bin/sh: ./runsolver/runsolverx64/runsolver: cannot execute binary file\
14:48:23.767 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:23.767 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Result for ParamILS: CRASHED, 0.00125098228455, -1, -1, 0\
14:48:23.767 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Output complete\
14:48:23.768 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Result: CRASHED,0.00125098228455\
14:48:23.768 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Instance was UNSAT, removing station.\
14:48:23.769 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Trying to add Station 4366 to current set.\
14:48:23.769 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Getting problem instance.\
14:48:23.769 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - Grouping stations.\
14:48:23.769 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - There are 1 groups.\
14:48:23.769 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Solving instance of size 2.\
14:48:23.770 [main] DEBUG c.u.c.b.a.t.d.BoundedTargetAlgorithmEvaluator - Asked for permission to run 1 things, got permission to run 1 things, total completed for this batch 0 \
14:48:23.770 [main] WARN  c.u.c.b.a.t.d.RetryCrashedRunsTargetAlgorithmEvaluator - Cannot retry runs that are asynchronous at the moment\
14:48:23.770 [pool-2-thread-1] DEBUG c.u.c.b.a.t.c.CommandLineTargetAlgorithmEvaluator - Using concurrent algorithm runner\
14:48:23.832 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected Call: cd /Users/narnosti/Documents/fcc-station-packing/FCCStationPacking/SATsolvers/ ;  python solverwrapper.py /Users/narnosti/Documents/fcc-station-packing/Output/CNFs/074a4c900e787bfd7baaeaadd262b0f315a633e0.cnf 0 1800.0 2147483647 0 -solver 'picosat' \
14:48:23.833 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected output last 4 lines\
14:48:23.833 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:23.833 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - /bin/sh: ./runsolver/runsolverx64/runsolver: cannot execute binary file\
14:48:23.833 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:23.833 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Result for ParamILS: CRASHED, 0.000916004180908, -1, -1, 0\
14:48:23.833 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Output complete\
14:48:23.834 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Result: CRASHED,9.16004180908E-4\
14:48:23.835 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Instance was UNSAT, removing station.\
14:48:23.835 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Trying to add Station 61214 to current set.\
14:48:23.835 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Getting problem instance.\
14:48:23.835 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - Grouping stations.\
14:48:23.835 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - There are 1 groups.\
14:48:23.836 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Solving instance of size 2.\
14:48:23.836 [main] DEBUG c.u.c.b.a.t.d.BoundedTargetAlgorithmEvaluator - Asked for permission to run 1 things, got permission to run 1 things, total completed for this batch 0 \
14:48:23.836 [main] WARN  c.u.c.b.a.t.d.RetryCrashedRunsTargetAlgorithmEvaluator - Cannot retry runs that are asynchronous at the moment\
14:48:23.836 [pool-2-thread-1] DEBUG c.u.c.b.a.t.c.CommandLineTargetAlgorithmEvaluator - Using concurrent algorithm runner\
14:48:23.917 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected Call: cd /Users/narnosti/Documents/fcc-station-packing/FCCStationPacking/SATsolvers/ ;  python solverwrapper.py /Users/narnosti/Documents/fcc-station-packing/Output/CNFs/5504738c941bd79d85347e736ad502a3e605165d.cnf 0 1800.0 2147483647 0 -solver 'picosat' \
14:48:23.917 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected output last 4 lines\
14:48:23.917 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:23.917 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - /bin/sh: ./runsolver/runsolverx64/runsolver: cannot execute binary file\
14:48:23.917 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:23.917 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Result for ParamILS: CRASHED, 0.000947952270508, -1, -1, 0\
14:48:23.917 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Output complete\
14:48:23.918 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Result: CRASHED,9.47952270508E-4\
14:48:23.919 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Instance was UNSAT, removing station.\
14:48:23.919 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Trying to add Station 66170 to current set.\
14:48:23.919 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Getting problem instance.\
14:48:23.919 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - Grouping stations.\
14:48:23.919 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - There are 1 groups.\
14:48:23.920 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Solving instance of size 2.\
14:48:23.920 [main] DEBUG c.u.c.b.a.t.d.BoundedTargetAlgorithmEvaluator - Asked for permission to run 1 things, got permission to run 1 things, total completed for this batch 0 \
14:48:23.920 [main] WARN  c.u.c.b.a.t.d.RetryCrashedRunsTargetAlgorithmEvaluator - Cannot retry runs that are asynchronous at the moment\
14:48:23.920 [pool-2-thread-1] DEBUG c.u.c.b.a.t.c.CommandLineTargetAlgorithmEvaluator - Using concurrent algorithm runner\
14:48:23.985 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected Call: cd /Users/narnosti/Documents/fcc-station-packing/FCCStationPacking/SATsolvers/ ;  python solverwrapper.py /Users/narnosti/Documents/fcc-station-packing/Output/CNFs/9181ee4af9cec759592d39fc72ac7d7717bf197b.cnf 0 1800.0 2147483647 0 -solver 'picosat' \
14:48:23.985 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected output last 4 lines\
14:48:23.985 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:23.985 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - /bin/sh: ./runsolver/runsolverx64/runsolver: cannot execute binary file\
14:48:23.985 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:23.985 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Result for ParamILS: CRASHED, 0.001296043396, -1, -1, 0\
14:48:23.985 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Output complete\
14:48:23.986 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Result: CRASHED,0.001296043396\
14:48:23.987 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Instance was UNSAT, removing station.\
14:48:23.987 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Trying to add Station 35277 to current set.\
14:48:23.987 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Getting problem instance.\
14:48:23.987 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - Grouping stations.\
14:48:23.987 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - There are 2 groups.\
14:48:23.988 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Solving instance of size 2.\
14:48:23.988 [main] DEBUG c.u.c.b.a.t.d.BoundedTargetAlgorithmEvaluator - Asked for permission to run 2 things, got permission to run 2 things, total completed for this batch 0 \
14:48:23.988 [main] WARN  c.u.c.b.a.t.d.RetryCrashedRunsTargetAlgorithmEvaluator - Cannot retry runs that are asynchronous at the moment\
14:48:23.988 [pool-2-thread-1] DEBUG c.u.c.b.a.t.c.CommandLineTargetAlgorithmEvaluator - Using concurrent algorithm runner\
14:48:23.988 [pool-2-thread-1] DEBUG c.u.c.b.a.a.AutomaticConfiguratorFactory - Concurrent Algorithm Runner created allowing \{\} threads\
14:48:23.989 [pool-2-thread-1] DEBUG c.u.c.b.a.a.ConcurrentAlgorithmRunner - Creating Thread Pool Supporting 4\
14:48:24.061 [pool-72-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected Call: cd /Users/narnosti/Documents/fcc-station-packing/FCCStationPacking/SATsolvers/ ;  python solverwrapper.py /Users/narnosti/Documents/fcc-station-packing/Output/CNFs/7ee55b71d880e20cfb3f9a9cd2b112e08b648742.cnf 0 1800.0 2147483647 0 -solver 'picosat' \
14:48:24.061 [pool-72-thread-2] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected Call: cd /Users/narnosti/Documents/fcc-station-packing/FCCStationPacking/SATsolvers/ ;  python solverwrapper.py /Users/narnosti/Documents/fcc-station-packing/Output/CNFs/fc7191c8f60045d9a545ac226dec3a8eb4a83b8d.cnf 0 1800.0 2147483647 0 -solver 'picosat' \
14:48:24.062 [pool-72-thread-2] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected output last 4 lines\
14:48:24.062 [pool-72-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected output last 4 lines\
14:48:24.062 [pool-72-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:24.062 [pool-72-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - /bin/sh: ./runsolver/runsolverx64/runsolver: cannot execute binary file\
14:48:24.062 [pool-72-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:24.062 [pool-72-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Result for ParamILS: CRASHED, 0.000911951065063, -1, -1, 0\
14:48:24.062 [pool-72-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Output complete\
14:48:24.062 [pool-72-thread-2] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:24.063 [pool-72-thread-2] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - /bin/sh: ./runsolver/runsolverx64/runsolver: cannot execute binary file\
14:48:24.063 [pool-72-thread-2] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:24.063 [pool-72-thread-2] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Result for ParamILS: CRASHED, 0.000381946563721, -1, -1, 0\
14:48:24.063 [pool-72-thread-2] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Output complete\
14:48:24.064 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Result: CRASHED,0.001293897628784\
14:48:24.064 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Instance was UNSAT, removing station.\
14:48:24.065 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Trying to add Station 66174 to current set.\
14:48:24.065 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Getting problem instance.\
14:48:24.065 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - Grouping stations.\
14:48:24.065 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - There are 1 groups.\
14:48:24.065 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Solving instance of size 2.\
14:48:24.066 [main] DEBUG c.u.c.b.a.t.d.BoundedTargetAlgorithmEvaluator - Asked for permission to run 1 things, got permission to run 1 things, total completed for this batch 0 \
14:48:24.066 [main] WARN  c.u.c.b.a.t.d.RetryCrashedRunsTargetAlgorithmEvaluator - Cannot retry runs that are asynchronous at the moment\
14:48:24.066 [pool-2-thread-1] DEBUG c.u.c.b.a.t.c.CommandLineTargetAlgorithmEvaluator - Using concurrent algorithm runner\
14:48:24.132 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected Call: cd /Users/narnosti/Documents/fcc-station-packing/FCCStationPacking/SATsolvers/ ;  python solverwrapper.py /Users/narnosti/Documents/fcc-station-packing/Output/CNFs/d9902d56723788717e0019583fe9c26911e9897b.cnf 0 1800.0 2147483647 0 -solver 'picosat' \
14:48:24.132 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected output last 4 lines\
14:48:24.132 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:24.132 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - /bin/sh: ./runsolver/runsolverx64/runsolver: cannot execute binary file\
14:48:24.132 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:24.132 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Result for ParamILS: CRASHED, 0.00101590156555, -1, -1, 0\
14:48:24.132 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Output complete\
14:48:24.133 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Result: CRASHED,0.00101590156555\
14:48:24.134 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Instance was UNSAT, removing station.\
14:48:24.134 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Trying to add Station 17544 to current set.\
14:48:24.134 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Getting problem instance.\
14:48:24.134 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - Grouping stations.\
14:48:24.134 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - There are 1 groups.\
14:48:24.135 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Solving instance of size 2.\
14:48:24.135 [main] DEBUG c.u.c.b.a.t.d.BoundedTargetAlgorithmEvaluator - Asked for permission to run 1 things, got permission to run 1 things, total completed for this batch 0 \
14:48:24.135 [main] WARN  c.u.c.b.a.t.d.RetryCrashedRunsTargetAlgorithmEvaluator - Cannot retry runs that are asynchronous at the moment\
14:48:24.135 [pool-2-thread-1] DEBUG c.u.c.b.a.t.c.CommandLineTargetAlgorithmEvaluator - Using concurrent algorithm runner\
14:48:24.198 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected Call: cd /Users/narnosti/Documents/fcc-station-packing/FCCStationPacking/SATsolvers/ ;  python solverwrapper.py /Users/narnosti/Documents/fcc-station-packing/Output/CNFs/f8b1f4020dc64d268b8718ee9fabf049b40ab24a.cnf 0 1800.0 2147483647 0 -solver 'picosat' \
14:48:24.199 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected output last 4 lines\
14:48:24.199 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:24.199 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - /bin/sh: ./runsolver/runsolverx64/runsolver: cannot execute binary file\
14:48:24.199 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:24.199 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Result for ParamILS: CRASHED, 0.000916004180908, -1, -1, 0\
14:48:24.199 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Output complete\
14:48:24.200 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Result: CRASHED,9.16004180908E-4\
14:48:24.201 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Instance was UNSAT, removing station.\
14:48:24.201 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Trying to add Station 39142 to current set.\
14:48:24.201 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Getting problem instance.\
14:48:24.201 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - Grouping stations.\
14:48:24.201 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - There are 1 groups.\
14:48:24.202 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Solving instance of size 2.\
14:48:24.202 [main] DEBUG c.u.c.b.a.t.d.BoundedTargetAlgorithmEvaluator - Asked for permission to run 1 things, got permission to run 1 things, total completed for this batch 0 \
14:48:24.203 [main] WARN  c.u.c.b.a.t.d.RetryCrashedRunsTargetAlgorithmEvaluator - Cannot retry runs that are asynchronous at the moment\
14:48:24.203 [pool-2-thread-1] DEBUG c.u.c.b.a.t.c.CommandLineTargetAlgorithmEvaluator - Using concurrent algorithm runner\
14:48:24.284 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected Call: cd /Users/narnosti/Documents/fcc-station-packing/FCCStationPacking/SATsolvers/ ;  python solverwrapper.py /Users/narnosti/Documents/fcc-station-packing/Output/CNFs/8f7d76f788b06ceb4fae7b32e047e2c39f9fae9c.cnf 0 1800.0 2147483647 0 -solver 'picosat' \
14:48:24.285 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected output last 4 lines\
14:48:24.285 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:24.285 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - /bin/sh: ./runsolver/runsolverx64/runsolver: cannot execute binary file\
14:48:24.285 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:24.285 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Result for ParamILS: CRASHED, 0.00115895271301, -1, -1, 0\
14:48:24.285 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Output complete\
14:48:24.286 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Result: CRASHED,0.00115895271301\
14:48:24.287 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Instance was UNSAT, removing station.\
14:48:24.287 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Trying to add Station 13060 to current set.\
14:48:24.287 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Getting problem instance.\
14:48:24.287 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - Grouping stations.\
14:48:24.287 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - There are 1 groups.\
14:48:24.287 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Solving instance of size 2.\
14:48:24.288 [main] DEBUG c.u.c.b.a.t.d.BoundedTargetAlgorithmEvaluator - Asked for permission to run 1 things, got permission to run 1 things, total completed for this batch 0 \
14:48:24.288 [main] WARN  c.u.c.b.a.t.d.RetryCrashedRunsTargetAlgorithmEvaluator - Cannot retry runs that are asynchronous at the moment\
14:48:24.288 [pool-2-thread-1] DEBUG c.u.c.b.a.t.c.CommandLineTargetAlgorithmEvaluator - Using concurrent algorithm runner\
14:48:24.354 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected Call: cd /Users/narnosti/Documents/fcc-station-packing/FCCStationPacking/SATsolvers/ ;  python solverwrapper.py /Users/narnosti/Documents/fcc-station-packing/Output/CNFs/f3c414e25b29323496c64d901661138d3bb58644.cnf 0 1800.0 2147483647 0 -solver 'picosat' \
14:48:24.354 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected output last 4 lines\
14:48:24.355 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:24.355 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - /bin/sh: ./runsolver/runsolverx64/runsolver: cannot execute binary file\
14:48:24.355 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:24.355 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Result for ParamILS: CRASHED, 0.00107789039612, -1, -1, 0\
14:48:24.355 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Output complete\
14:48:24.356 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Result: CRASHED,0.00107789039612\
14:48:24.356 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Instance was UNSAT, removing station.\
14:48:24.356 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Trying to add Station 70482 to current set.\
14:48:24.356 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Getting problem instance.\
14:48:24.356 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - Grouping stations.\
14:48:24.356 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - There are 1 groups.\
14:48:24.357 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Solving instance of size 2.\
14:48:24.357 [main] DEBUG c.u.c.b.a.t.d.BoundedTargetAlgorithmEvaluator - Asked for permission to run 1 things, got permission to run 1 things, total completed for this batch 0 \
14:48:24.357 [main] WARN  c.u.c.b.a.t.d.RetryCrashedRunsTargetAlgorithmEvaluator - Cannot retry runs that are asynchronous at the moment\
14:48:24.358 [pool-2-thread-1] DEBUG c.u.c.b.a.t.c.CommandLineTargetAlgorithmEvaluator - Using concurrent algorithm runner\
14:48:24.433 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected Call: cd /Users/narnosti/Documents/fcc-station-packing/FCCStationPacking/SATsolvers/ ;  python solverwrapper.py /Users/narnosti/Documents/fcc-station-packing/Output/CNFs/56ac72c46988bc3f94608cae5f663a4080f62668.cnf 0 1800.0 2147483647 0 -solver 'picosat' \
14:48:24.433 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected output last 4 lines\
14:48:24.433 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:24.433 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - /bin/sh: ./runsolver/runsolverx64/runsolver: cannot execute binary file\
14:48:24.433 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:24.433 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Result for ParamILS: CRASHED, 0.00107383728027, -1, -1, 0\
14:48:24.434 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Output complete\
14:48:24.434 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Result: CRASHED,0.00107383728027\
14:48:24.435 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Instance was UNSAT, removing station.\
14:48:24.435 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Trying to add Station 87 to current set.\
14:48:24.435 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Getting problem instance.\
14:48:24.435 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - Grouping stations.\
14:48:24.435 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - There are 1 groups.\
14:48:24.436 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Solving instance of size 2.\
14:48:24.436 [main] DEBUG c.u.c.b.a.t.d.BoundedTargetAlgorithmEvaluator - Asked for permission to run 1 things, got permission to run 1 things, total completed for this batch 0 \
14:48:24.436 [main] WARN  c.u.c.b.a.t.d.RetryCrashedRunsTargetAlgorithmEvaluator - Cannot retry runs that are asynchronous at the moment\
14:48:24.436 [pool-2-thread-1] DEBUG c.u.c.b.a.t.c.CommandLineTargetAlgorithmEvaluator - Using concurrent algorithm runner\
14:48:24.494 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected Call: cd /Users/narnosti/Documents/fcc-station-packing/FCCStationPacking/SATsolvers/ ;  python solverwrapper.py /Users/narnosti/Documents/fcc-station-packing/Output/CNFs/4ae7e0917e6be786c77840f1e33e5d1fdbde9f4a.cnf 0 1800.0 2147483647 0 -solver 'picosat' \
14:48:24.494 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected output last 4 lines\
14:48:24.494 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:24.494 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - /bin/sh: ./runsolver/runsolverx64/runsolver: cannot execute binary file\
14:48:24.494 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:24.494 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Result for ParamILS: CRASHED, 0.000968933105469, -1, -1, 0\
14:48:24.495 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Output complete\
14:48:24.496 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Result: CRASHED,9.68933105469E-4\
14:48:24.496 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Instance was UNSAT, removing station.\
14:48:24.496 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Trying to add Station 35283 to current set.\
14:48:24.496 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Getting problem instance.\
14:48:24.496 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - Grouping stations.\
14:48:24.496 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - There are 1 groups.\
14:48:24.497 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Solving instance of size 2.\
14:48:24.497 [main] DEBUG c.u.c.b.a.t.d.BoundedTargetAlgorithmEvaluator - Asked for permission to run 1 things, got permission to run 1 things, total completed for this batch 0 \
14:48:24.497 [main] WARN  c.u.c.b.a.t.d.RetryCrashedRunsTargetAlgorithmEvaluator - Cannot retry runs that are asynchronous at the moment\
14:48:24.497 [pool-2-thread-1] DEBUG c.u.c.b.a.t.c.CommandLineTargetAlgorithmEvaluator - Using concurrent algorithm runner\
14:48:24.563 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected Call: cd /Users/narnosti/Documents/fcc-station-packing/FCCStationPacking/SATsolvers/ ;  python solverwrapper.py /Users/narnosti/Documents/fcc-station-packing/Output/CNFs/3e35e1ab7b865edc1c614bf40e206618f8f5a2bd.cnf 0 1800.0 2147483647 0 -solver 'picosat' \
14:48:24.563 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected output last 4 lines\
14:48:24.563 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:24.563 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - /bin/sh: ./runsolver/runsolverx64/runsolver: cannot execute binary file\
14:48:24.563 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:24.563 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Result for ParamILS: CRASHED, 0.000895023345947, -1, -1, 0\
14:48:24.563 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Output complete\
14:48:24.564 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Result: CRASHED,8.95023345947E-4\
14:48:24.565 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Instance was UNSAT, removing station.\
14:48:24.565 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Trying to add Station 43952 to current set.\
14:48:24.565 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Getting problem instance.\
14:48:24.565 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - Grouping stations.\
14:48:24.565 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - There are 1 groups.\
14:48:24.565 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Solving instance of size 2.\
14:48:24.566 [main] DEBUG c.u.c.b.a.t.d.BoundedTargetAlgorithmEvaluator - Asked for permission to run 1 things, got permission to run 1 things, total completed for this batch 0 \
14:48:24.566 [main] WARN  c.u.c.b.a.t.d.RetryCrashedRunsTargetAlgorithmEvaluator - Cannot retry runs that are asynchronous at the moment\
14:48:24.566 [pool-2-thread-1] DEBUG c.u.c.b.a.t.c.CommandLineTargetAlgorithmEvaluator - Using concurrent algorithm runner\
14:48:24.630 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected Call: cd /Users/narnosti/Documents/fcc-station-packing/FCCStationPacking/SATsolvers/ ;  python solverwrapper.py /Users/narnosti/Documents/fcc-station-packing/Output/CNFs/a371115b4be181d3067a00cb2939f05a5ec9b9ca.cnf 0 1800.0 2147483647 0 -solver 'picosat' \
14:48:24.630 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected output last 4 lines\
14:48:24.630 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:24.630 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - /bin/sh: ./runsolver/runsolverx64/runsolver: cannot execute binary file\
14:48:24.630 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:24.630 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Result for ParamILS: CRASHED, 0.00113010406494, -1, -1, 0\
14:48:24.631 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Output complete\
14:48:24.631 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Result: CRASHED,0.00113010406494\
14:48:24.632 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Instance was UNSAT, removing station.\
14:48:24.632 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Trying to add Station 13058 to current set.\
14:48:24.632 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Getting problem instance.\
14:48:24.632 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - Grouping stations.\
14:48:24.632 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - There are 2 groups.\
14:48:24.633 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Solving instance of size 2.\
14:48:24.633 [main] DEBUG c.u.c.b.a.t.d.BoundedTargetAlgorithmEvaluator - Asked for permission to run 2 things, got permission to run 2 things, total completed for this batch 0 \
14:48:24.633 [main] WARN  c.u.c.b.a.t.d.RetryCrashedRunsTargetAlgorithmEvaluator - Cannot retry runs that are asynchronous at the moment\
14:48:24.633 [pool-2-thread-1] DEBUG c.u.c.b.a.t.c.CommandLineTargetAlgorithmEvaluator - Using concurrent algorithm runner\
14:48:24.633 [pool-2-thread-1] DEBUG c.u.c.b.a.a.AutomaticConfiguratorFactory - Concurrent Algorithm Runner created allowing \{\} threads\
14:48:24.634 [pool-2-thread-1] DEBUG c.u.c.b.a.a.ConcurrentAlgorithmRunner - Creating Thread Pool Supporting 4\
14:48:24.717 [pool-92-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected Call: cd /Users/narnosti/Documents/fcc-station-packing/FCCStationPacking/SATsolvers/ ;  python solverwrapper.py /Users/narnosti/Documents/fcc-station-packing/Output/CNFs/7ee55b71d880e20cfb3f9a9cd2b112e08b648742.cnf 0 1800.0 2147483647 0 -solver 'picosat' \
14:48:24.717 [pool-92-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected output last 4 lines\
14:48:24.717 [pool-92-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:24.717 [pool-92-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - /bin/sh: ./runsolver/runsolverx64/runsolver: cannot execute binary file\
14:48:24.717 [pool-92-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:24.717 [pool-92-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Result for ParamILS: CRASHED, 0.00327110290527, -1, -1, 0\
14:48:24.717 [pool-92-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Output complete\
14:48:24.721 [pool-92-thread-2] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected Call: cd /Users/narnosti/Documents/fcc-station-packing/FCCStationPacking/SATsolvers/ ;  python solverwrapper.py /Users/narnosti/Documents/fcc-station-packing/Output/CNFs/4f43d33abdc54e08e2f6bad067d8eff1b308d6d9.cnf 0 1800.0 2147483647 0 -solver 'picosat' \
14:48:24.721 [pool-92-thread-2] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected output last 4 lines\
14:48:24.721 [pool-92-thread-2] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:24.721 [pool-92-thread-2] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - /bin/sh: ./runsolver/runsolverx64/runsolver: cannot execute binary file\
14:48:24.721 [pool-92-thread-2] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:24.722 [pool-92-thread-2] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Result for ParamILS: CRASHED, 0.0016040802002, -1, -1, 0\
14:48:24.722 [pool-92-thread-2] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Output complete\
14:48:24.722 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Result: CRASHED,0.00487518310547\
14:48:24.723 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Instance was UNSAT, removing station.\
14:48:24.723 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Trying to add Station 70491 to current set.\
14:48:24.723 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Getting problem instance.\
14:48:24.723 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - Grouping stations.\
14:48:24.723 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - There are 1 groups.\
14:48:24.724 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Solving instance of size 2.\
14:48:24.724 [main] DEBUG c.u.c.b.a.t.d.BoundedTargetAlgorithmEvaluator - Asked for permission to run 1 things, got permission to run 1 things, total completed for this batch 0 \
14:48:24.724 [main] WARN  c.u.c.b.a.t.d.RetryCrashedRunsTargetAlgorithmEvaluator - Cannot retry runs that are asynchronous at the moment\
14:48:24.724 [pool-2-thread-1] DEBUG c.u.c.b.a.t.c.CommandLineTargetAlgorithmEvaluator - Using concurrent algorithm runner\
14:48:24.789 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected Call: cd /Users/narnosti/Documents/fcc-station-packing/FCCStationPacking/SATsolvers/ ;  python solverwrapper.py /Users/narnosti/Documents/fcc-station-packing/Output/CNFs/cfa573c8ea0e5f983d08d901e186aa08140b05bd.cnf 0 1800.0 2147483647 0 -solver 'picosat' \
14:48:24.790 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected output last 4 lines\
14:48:24.790 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:24.790 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - /bin/sh: ./runsolver/runsolverx64/runsolver: cannot execute binary file\
14:48:24.790 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:24.790 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Result for ParamILS: CRASHED, 0.00102996826172, -1, -1, 0\
14:48:24.790 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Output complete\
14:48:24.791 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Result: CRASHED,0.00102996826172\
14:48:24.791 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Instance was UNSAT, removing station.\
14:48:24.791 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Trying to add Station 70493 to current set.\
14:48:24.791 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Getting problem instance.\
14:48:24.791 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - Grouping stations.\
14:48:24.791 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - There are 1 groups.\
14:48:24.792 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Solving instance of size 2.\
14:48:24.792 [main] DEBUG c.u.c.b.a.t.d.BoundedTargetAlgorithmEvaluator - Asked for permission to run 1 things, got permission to run 1 things, total completed for this batch 0 \
14:48:24.792 [main] WARN  c.u.c.b.a.t.d.RetryCrashedRunsTargetAlgorithmEvaluator - Cannot retry runs that are asynchronous at the moment\
14:48:24.792 [pool-2-thread-1] DEBUG c.u.c.b.a.t.c.CommandLineTargetAlgorithmEvaluator - Using concurrent algorithm runner\
14:48:24.850 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected Call: cd /Users/narnosti/Documents/fcc-station-packing/FCCStationPacking/SATsolvers/ ;  python solverwrapper.py /Users/narnosti/Documents/fcc-station-packing/Output/CNFs/36f616febb4fd37b6e061bc73fe687415c3e478f.cnf 0 1800.0 2147483647 0 -solver 'picosat' \
14:48:24.851 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected output last 4 lines\
14:48:24.851 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:24.851 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - /bin/sh: ./runsolver/runsolverx64/runsolver: cannot execute binary file\
14:48:24.851 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:24.851 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Result for ParamILS: CRASHED, 0.000953912734985, -1, -1, 0\
14:48:24.851 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Output complete\
14:48:24.852 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Result: CRASHED,9.53912734985E-4\
14:48:24.853 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Instance was UNSAT, removing station.\
14:48:24.853 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Trying to add Station 70492 to current set.\
14:48:24.853 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Getting problem instance.\
14:48:24.853 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - Grouping stations.\
14:48:24.853 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - There are 1 groups.\
14:48:24.854 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Solving instance of size 2.\
14:48:24.854 [main] DEBUG c.u.c.b.a.t.d.BoundedTargetAlgorithmEvaluator - Asked for permission to run 1 things, got permission to run 1 things, total completed for this batch 0 \
14:48:24.854 [main] WARN  c.u.c.b.a.t.d.RetryCrashedRunsTargetAlgorithmEvaluator - Cannot retry runs that are asynchronous at the moment\
14:48:24.854 [pool-2-thread-1] DEBUG c.u.c.b.a.t.c.CommandLineTargetAlgorithmEvaluator - Using concurrent algorithm runner\
14:48:24.923 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected Call: cd /Users/narnosti/Documents/fcc-station-packing/FCCStationPacking/SATsolvers/ ;  python solverwrapper.py /Users/narnosti/Documents/fcc-station-packing/Output/CNFs/a5b52e4dc69dad3f237df2b2aeca53d0d4f36bcb.cnf 0 1800.0 2147483647 0 -solver 'picosat' \
14:48:24.923 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected output last 4 lines\
14:48:24.923 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:24.923 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - /bin/sh: ./runsolver/runsolverx64/runsolver: cannot execute binary file\
14:48:24.923 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:24.923 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Result for ParamILS: CRASHED, 0.0012149810791, -1, -1, 0\
14:48:24.923 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Output complete\
14:48:24.924 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Result: CRASHED,0.0012149810791\
14:48:24.930 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Instance was UNSAT, removing station.\
14:48:24.930 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Trying to add Station 65143 to current set.\
14:48:24.930 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Getting problem instance.\
14:48:24.930 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - Grouping stations.\
14:48:24.930 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - There are 1 groups.\
14:48:24.931 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Solving instance of size 2.\
14:48:24.931 [main] DEBUG c.u.c.b.a.t.d.BoundedTargetAlgorithmEvaluator - Asked for permission to run 1 things, got permission to run 1 things, total completed for this batch 0 \
14:48:24.931 [main] WARN  c.u.c.b.a.t.d.RetryCrashedRunsTargetAlgorithmEvaluator - Cannot retry runs that are asynchronous at the moment\
14:48:24.931 [pool-2-thread-1] DEBUG c.u.c.b.a.t.c.CommandLineTargetAlgorithmEvaluator - Using concurrent algorithm runner\
14:48:24.998 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected Call: cd /Users/narnosti/Documents/fcc-station-packing/FCCStationPacking/SATsolvers/ ;  python solverwrapper.py /Users/narnosti/Documents/fcc-station-packing/Output/CNFs/fb347c1d097f7195fd684017d4e7a5986943edd9.cnf 0 1800.0 2147483647 0 -solver 'picosat' \
14:48:24.998 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Failed Run Detected output last 4 lines\
14:48:24.998 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:24.999 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - /bin/sh: ./runsolver/runsolverx64/runsolver: cannot execute binary file\
14:48:24.999 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - \
14:48:24.999 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Result for ParamILS: CRASHED, 0.000996112823486, -1, -1, 0\
14:48:24.999 [pool-2-thread-1] INFO  c.u.c.b.a.a.CommandLineAlgorithmRun - Output complete\
14:48:24.999 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Result: CRASHED,9.96112823486E-4\
14:48:25.000 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Instance was UNSAT, removing station.\
14:48:25.000 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Trying to add Station 26304 to current set.\
14:48:25.000 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Getting problem instance.\
14:48:25.000 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - Grouping stations.\
14:48:25.000 [main] INFO  c.u.c.b.s.e.i.InstanceEncoder - There are 1 groups.\
14:48:25.000 [main] INFO  c.u.c.b.s.e.InstanceGeneration - Solving instance of size 2.\
14:48:25.001 [main] DEBUG c.u.c.b.a.t.d.BoundedTargetAlgorithmEvaluator - Asked for permission to run 1 things, got permission to run 1 things, total completed for this batch 0 \
14:48:25.001 [main] WARN  c.u.c.b.a.t.d.RetryCrashedRunsTargetAlgorithmEvaluator - Cannot retry runs that are asynchronous at the moment\
14:48:25.001 [pool-2-thread-1] DEBUG c.u.c.b.a.t.c.CommandLineTargetAlgorithmEvaluator - Using concurrent algorithm runner}